version: 2
updates:
  - directory: "/"
    package-ecosystem: pip
    versioning-strategy: increase-if-necessary
    schedule:
      interval: weekly
    labels: [deps]
    groups:
      default:
        update-types:
        - "minor"
        - "patch"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
